cmd_spl/u-boot-spl.lds := arm-linux-gnueabi-gcc -E -Wp,-MD,spl/.u-boot-spl.lds.d -DCONFIG_SPL_BUILD   -pipe -D__LINUX_ARM_ARCH__=     -include include/u-boot/u-boot.lds.h -include include/config.h  -DCPUDIR=arch/arm/cpu/armv7 -ansi -D__ASSEMBLY__ -x assembler-with-cpp -std=c99 -P -o spl/u-boot-spl.lds board/samsung/common/exynos-uboot-spl.lds

source_spl/u-boot-spl.lds := board/samsung/common/exynos-uboot-spl.lds

deps_spl/u-boot-spl.lds := \
    $(wildcard include/config/spl/max/footprint.h) \
  /usr/arm-linux-gnueabi/include/stdc-predef.h \
  include/u-boot/u-boot.lds.h \
  include/config.h \
    $(wildcard include/config/boarddir.h) \
  include/config_defaults.h \
    $(wildcard include/config/defaults/h/.h) \
    $(wildcard include/config/bootm/linux.h) \
    $(wildcard include/config/bootm/netbsd.h) \
    $(wildcard include/config/bootm/plan9.h) \
    $(wildcard include/config/bootm/rtems.h) \
    $(wildcard include/config/bootm/vxworks.h) \
    $(wildcard include/config/gzip.h) \
    $(wildcard include/config/zlib.h) \
  include/config_uncmd_spl.h \
    $(wildcard include/config/uncmd/spl/h//.h) \
    $(wildcard include/config/spl/build.h) \
    $(wildcard include/config/spl/dm.h) \
    $(wildcard include/config/dm/serial.h) \
    $(wildcard include/config/dm/gpio.h) \
    $(wildcard include/config/dm/i2c.h) \
    $(wildcard include/config/dm/spi.h) \
    $(wildcard include/config/dm/warn.h) \
    $(wildcard include/config/dm/stdio.h) \
  include/configs/midas.h \
    $(wildcard include/config/h//.h) \
    $(wildcard include/config/exynos4.h) \
    $(wildcard include/config/sys/l2cache/off.h) \
    $(wildcard include/config/sys/l2/pl310.h) \
    $(wildcard include/config/sys/pl310/base.h) \
    $(wildcard include/config/misc/common.h) \
    $(wildcard include/config/misc/init/r.h) \
    $(wildcard include/config/env/vars/uboot/runtime/config.h) \
    $(wildcard include/config/revision/tag.h) \
    $(wildcard include/config/nr/dram/banks.h) \
    $(wildcard include/config/sys/sdram/base.h) \
    $(wildcard include/config/sys/load/addr.h) \
    $(wildcard include/config/exynos/spl.h) \
    $(wildcard include/config/spl/text/base.h) \
    $(wildcard include/config/spl/stack.h) \
    $(wildcard include/config/iram/top.h) \
    $(wildcard include/config/sys/init/sp/addr.h) \
    $(wildcard include/config/res/block/size.h) \
    $(wildcard include/config/bl1/size.h) \
    $(wildcard include/config/spl/size.h) \
    $(wildcard include/config/bl2/size.h) \
    $(wildcard include/config/bl2/offset.h) \
    $(wildcard include/config/sys/mmc/env/dev.h) \
    $(wildcard include/config/sys/mmc/env/part.h) \
    $(wildcard include/config/env/size.h) \
    $(wildcard include/config/env/offset.h) \
    $(wildcard include/config/support/emmc/boot.h) \
    $(wildcard include/config/ipaddr.h) \
    $(wildcard include/config/extra/env/settings.h) \
    $(wildcard include/config/baudrate.h) \
  include/configs/exynos4-common.h \
    $(wildcard include/config/exynos4/common/h.h) \
    $(wildcard include/config/board/common.h) \
    $(wildcard include/config/mmc/default/dev.h) \
    $(wildcard include/config/sys/dfu/data/buf/size.h) \
    $(wildcard include/config/g/dnl/thor/vendor/num.h) \
    $(wildcard include/config/g/dnl/thor/product/num.h) \
    $(wildcard include/config/g/dnl/ums/vendor/num.h) \
    $(wildcard include/config/g/dnl/ums/product/num.h) \
    $(wildcard include/config/sys/monitor/len.h) \
    $(wildcard include/config/usb/gadget/dwc2/otg/phy.h) \
    $(wildcard include/config/extra/env/itb.h) \
  include/configs/exynos-common.h \
    $(wildcard include/config/samsung.h) \
    $(wildcard include/config/s5p.h) \
    $(wildcard include/config/arch/cpu/init.h) \
    $(wildcard include/config/skip/lowlevel/init.h) \
    $(wildcard include/config/sys/clk/freq.h) \
    $(wildcard include/config/setup/memory/tags.h) \
    $(wildcard include/config/cmdline/tag.h) \
    $(wildcard include/config/initrd/tag.h) \
    $(wildcard include/config/env/overwrite.h) \
    $(wildcard include/config/sys/malloc/len.h) \
    $(wildcard include/config/pwm.h) \
    $(wildcard include/config/sys/cbsize.h) \
    $(wildcard include/config/sys/pbsize.h) \
    $(wildcard include/config/sys/bargsize.h) \
    $(wildcard include/config/h.h) \
  include/configs/asm/arch/cpu.h \
    $(wildcard include/config/base.h) \
  include/configs/linux/sizes.h \
  /usr/arm-linux-gnueabi/include/linux/const.h \
  include/asm/config.h \
    $(wildcard include/config/h/.h) \
    $(wildcard include/config/lmb.h) \
    $(wildcard include/config/sys/boot/ramdisk/high.h) \
    $(wildcard include/config/arch/ls1021a.h) \
    $(wildcard include/config/cpu/pxa27x.h) \
    $(wildcard include/config/cpu/monahans.h) \
    $(wildcard include/config/cpu/pxa25x.h) \
    $(wildcard include/config/fsl/layerscape.h) \
  include/linux/generated/autoconf.h \
    $(wildcard include/config/display/boardinfo.h) \
    $(wildcard include/config/cmd/bootm.h) \
    $(wildcard include/config/cmd/ext4.h) \
    $(wildcard include/config/sys/arm/mmu.h) \
    $(wildcard include/config/bootstage/record/count.h) \
    $(wildcard include/config/image/sparse/fillbuf/size.h) \
    $(wildcard include/config/cmd/fastboot.h) \
    $(wildcard include/config/loglevel.h) \
    $(wildcard include/config/debug/uart/announce.h) \
    $(wildcard include/config/of/board/setup.h) \
    $(wildcard include/config/mtdids/default.h) \
    $(wildcard include/config/of/libfdt.h) \
    $(wildcard include/config/cmd/editenv.h) \
    $(wildcard include/config/spl/use/arch/memset.h) \
    $(wildcard include/config/fastboot/flash.h) \
    $(wildcard include/config/log/console.h) \
    $(wildcard include/config/bootp/pxe/clientarch.h) \
    $(wildcard include/config/use/arch/memcpy.h) \
    $(wildcard include/config/blk.h) \
    $(wildcard include/config/usb.h) \
    $(wildcard include/config/tpl/loglevel.h) \
    $(wildcard include/config/arm/asm/unified.h) \
    $(wildcard include/config/of/libfdt/overlay.h) \
    $(wildcard include/config/of/separate.h) \
    $(wildcard include/config/console/mux.h) \
    $(wildcard include/config/generate/smbios/table.h) \
    $(wildcard include/config/sha1.h) \
    $(wildcard include/config/fastboot/gpt/name.h) \
    $(wildcard include/config/dm/regulator.h) \
    $(wildcard include/config/exynos4412.h) \
    $(wildcard include/config/hash.h) \
    $(wildcard include/config/cmd/console.h) \
    $(wildcard include/config/cmd/bootd.h) \
    $(wildcard include/config/netconsole.h) \
    $(wildcard include/config/efi/unicode/capitalization.h) \
    $(wildcard include/config/default/fdt/file.h) \
    $(wildcard include/config/dm/extcon/max77693.h) \
    $(wildcard include/config/of/translate.h) \
    $(wildcard include/config/bootstage/stash/addr.h) \
    $(wildcard include/config/smbios/manufacturer.h) \
    $(wildcard include/config/spl/sprintf.h) \
    $(wildcard include/config/have/private/libgcc.h) \
    $(wildcard include/config/cmd/bdi.h) \
    $(wildcard include/config/arm.h) \
    $(wildcard include/config/create/arch/symlink.h) \
    $(wildcard include/config/dm/seq/alias.h) \
    $(wildcard include/config/sys/vendor.h) \
    $(wildcard include/config/usb/storage.h) \
    $(wildcard include/config/specify/console/index.h) \
    $(wildcard include/config/cmd/bootefi/hello/compile.h) \
    $(wildcard include/config/efi/loader.h) \
    $(wildcard include/config/spi.h) \
    $(wildcard include/config/cmd/ping.h) \
    $(wildcard include/config/usb/gadget/vendor/num.h) \
    $(wildcard include/config/dtc.h) \
    $(wildcard include/config/fit/external/offset.h) \
    $(wildcard include/config/usb/function/mass/storage.h) \
    $(wildcard include/config/of/list.h) \
    $(wildcard include/config/cmd/saveenv.h) \
    $(wildcard include/config/debug/uart/shift.h) \
    $(wildcard include/config/cmd/clk.h) \
    $(wildcard include/config/dm/regulator/fixed.h) \
    $(wildcard include/config/fastboot/usb/dev.h) \
    $(wildcard include/config/cmd/misc.h) \
    $(wildcard include/config/sys/cpu.h) \
    $(wildcard include/config/sys/console/is/in/env.h) \
    $(wildcard include/config/bootp/pxe.h) \
    $(wildcard include/config/fastboot/flash/mmc/dev.h) \
    $(wildcard include/config/usb/gadget/product/num.h) \
    $(wildcard include/config/cc/optimize/for/size.h) \
    $(wildcard include/config/debug/uart/base.h) \
    $(wildcard include/config/dm/mmc.h) \
    $(wildcard include/config/spl/serial/support.h) \
    $(wildcard include/config/use/private/libgcc.h) \
    $(wildcard include/config/arch/fixup/fdt/memory.h) \
    $(wildcard include/config/build/target.h) \
    $(wildcard include/config/dm/regulator/max77686.h) \
    $(wildcard include/config/cmd/flash.h) \
    $(wildcard include/config/cmd/tftpput.h) \
    $(wildcard include/config/usb/gadget/manufacturer.h) \
    $(wildcard include/config/regex.h) \
    $(wildcard include/config/efi/partition/entries/numbers.h) \
    $(wildcard include/config/debug/uart/s5p.h) \
    $(wildcard include/config/cmd/env/exists.h) \
    $(wildcard include/config/dm/extcon.h) \
    $(wildcard include/config/smbios/product/name.h) \
    $(wildcard include/config/ident/string.h) \
    $(wildcard include/config/tpl/sys/malloc/f/len.h) \
    $(wildcard include/config/bootp/dns.h) \
    $(wildcard include/config/cmdline/editing.h) \
    $(wildcard include/config/cmd/setexpr.h) \
    $(wildcard include/config/sys/console/info/quiet.h) \
    $(wildcard include/config/dm/device/remove.h) \
    $(wildcard include/config/cmd/led.h) \
    $(wildcard include/config/sys/cacheline/size.h) \
    $(wildcard include/config/cmd/exportenv.h) \
    $(wildcard include/config/cmd/mmc.h) \
    $(wildcard include/config/dm/dev/read/inline.h) \
    $(wildcard include/config/cmd/usb/mass/storage.h) \
    $(wildcard include/config/fastboot/flash/mmc.h) \
    $(wildcard include/config/pinctrl.h) \
    $(wildcard include/config/require/serial/console.h) \
    $(wildcard include/config/env/is/in/mmc.h) \
    $(wildcard include/config/dm/pmic/max77686.h) \
    $(wildcard include/config/usb/gadget.h) \
    $(wildcard include/config/optee/tzdram/size.h) \
    $(wildcard include/config/usb/eth/rndis.h) \
    $(wildcard include/config/spl/efi/partition.h) \
    $(wildcard include/config/log/max/level.h) \
    $(wildcard include/config/zynq/gem/i2c/mac/offset.h) \
    $(wildcard include/config/arch/exynos4.h) \
    $(wildcard include/config/cmd/dhcp.h) \
    $(wildcard include/config/fs/fat.h) \
    $(wildcard include/config/bootp/hostname.h) \
    $(wildcard include/config/sd/boot.h) \
    $(wildcard include/config/saved/dram/timing/base.h) \
    $(wildcard include/config/cmd/extcon.h) \
    $(wildcard include/config/debug/uart.h) \
    $(wildcard include/config/dm/pmic/max77693.h) \
    $(wildcard include/config/sys/extra/options.h) \
    $(wildcard include/config/efi/partition.h) \
    $(wildcard include/config/cmd/part.h) \
    $(wildcard include/config/auto/complete.h) \
    $(wildcard include/config/spl/serial/present.h) \
    $(wildcard include/config/simple/bus.h) \
    $(wildcard include/config/log/default/level.h) \
    $(wildcard include/config/dm/regulator/max77693.h) \
    $(wildcard include/config/have/block/device.h) \
    $(wildcard include/config/tpl/serial/present.h) \
    $(wildcard include/config/cmd/crc32.h) \
    $(wildcard include/config/printf.h) \
    $(wildcard include/config/usb/gadget/vbus/draw.h) \
    $(wildcard include/config/bootp/bootpath.h) \
    $(wildcard include/config/sys/board.h) \
    $(wildcard include/config/cmd/i2c.h) \
    $(wildcard include/config/mmc/sdhci/s5p.h) \
    $(wildcard include/config/fastboot.h) \
    $(wildcard include/config/sys/config/name.h) \
    $(wildcard include/config/name.h) \
    $(wildcard include/config/led.h) \
    $(wildcard include/config/cmd/bootp.h) \
    $(wildcard include/config/cmd/nfs.h) \
    $(wildcard include/config/fit/enable/sha256/support.h) \
    $(wildcard include/config/usb/gadget/dualspeed.h) \
    $(wildcard include/config/mmc/quirks.h) \
    $(wildcard include/config/dm/i2c/gpio.h) \
    $(wildcard include/config/dfu.h) \
    $(wildcard include/config/use/arch/memset.h) \
    $(wildcard include/config/net.h) \
    $(wildcard include/config/sha256.h) \
    $(wildcard include/config/pinmux.h) \
    $(wildcard include/config/dm/charger/max77693.h) \
    $(wildcard include/config/bootp/subnetmask.h) \
    $(wildcard include/config/android/boot/image.h) \
    $(wildcard include/config/spl/of/libfdt.h) \
    $(wildcard include/config/mmc/dw.h) \
    $(wildcard include/config/partition/uuids.h) \
    $(wildcard include/config/env/vars/uboot/config.h) \
    $(wildcard include/config/sys/arm/cache/cp15.h) \
    $(wildcard include/config/cmd/go.h) \
    $(wildcard include/config/cmd/dfu.h) \
    $(wildcard include/config/usbnet/host/addr.h) \
    $(wildcard include/config/board/early/init/f.h) \
    $(wildcard include/config/sys/i2c/s3c24x0.h) \
    $(wildcard include/config/sys/malloc/clear/on/init.h) \
    $(wildcard include/config/bootdelay.h) \
    $(wildcard include/config/cmd/imi.h) \
    $(wildcard include/config/sys/hz.h) \
    $(wildcard include/config/fit/best/match.h) \
    $(wildcard include/config/cmd/fs/generic.h) \
    $(wildcard include/config/sprintf.h) \
    $(wildcard include/config/support/of/control.h) \
    $(wildcard include/config/spl/bootstage/record/count.h) \
    $(wildcard include/config/debug/uart/clock.h) \
    $(wildcard include/config/cmd/read.h) \
    $(wildcard include/config/distro/defaults.h) \
    $(wildcard include/config/sys/longhelp.h) \
    $(wildcard include/config/dm/battery/max17047.h) \
    $(wildcard include/config/cmd/ext2.h) \
    $(wildcard include/config/localversion.h) \
    $(wildcard include/config/cmd/log.h) \
    $(wildcard include/config/spl/strto.h) \
    $(wildcard include/config/usb/gadget/download.h) \
    $(wildcard include/config/support/spl.h) \
    $(wildcard include/config/cmdline.h) \
    $(wildcard include/config/spl/libcommon/support.h) \
    $(wildcard include/config/spl/banner/print.h) \
    $(wildcard include/config/usb/ether.h) \
    $(wildcard include/config/cmd/loadb.h) \
    $(wildcard include/config/cmd/run.h) \
    $(wildcard include/config/cmd/pinmux.h) \
    $(wildcard include/config/fastboot/buf/addr.h) \
    $(wildcard include/config/fs/fat/max/clustsize.h) \
    $(wildcard include/config/dm/battery.h) \
    $(wildcard include/config/sys/prompt.h) \
    $(wildcard include/config/sys/text/base.h) \
    $(wildcard include/config/cmd/tftpsrv.h) \
    $(wildcard include/config/cmd/memory.h) \
    $(wildcard include/config/hush/parser.h) \
    $(wildcard include/config/cmd/bootz.h) \
    $(wildcard include/config/board/late/init.h) \
    $(wildcard include/config/cmd/ximg.h) \
    $(wildcard include/config/cmd/echo.h) \
    $(wildcard include/config/fastboot/buf/size.h) \
    $(wildcard include/config/led/an30259a.h) \
    $(wildcard include/config/spl.h) \
    $(wildcard include/config/mmc/write.h) \
    $(wildcard include/config/dm/pmic.h) \
    $(wildcard include/config/localversion/auto.h) \
    $(wildcard include/config/target/midas.h) \
    $(wildcard include/config/spl/sys/malloc/f/len.h) \
    $(wildcard include/config/sys/arch.h) \
    $(wildcard include/config/md5.h) \
    $(wildcard include/config/cmd/dm.h) \
    $(wildcard include/config/cmd/charger.h) \
    $(wildcard include/config/lib/uuid.h) \
    $(wildcard include/config/sys/cache/shift/6.h) \
    $(wildcard include/config/usbnet/devaddr.h) \
    $(wildcard include/config/has/vbar.h) \
    $(wildcard include/config/cpu/v7a.h) \
    $(wildcard include/config/expert.h) \
    $(wildcard include/config/multi/dtb/fit.h) \
    $(wildcard include/config/mmc/dw/exynos.h) \
    $(wildcard include/config/mmc/verbose.h) \
    $(wildcard include/config/sys/soc.h) \
    $(wildcard include/config/mmc.h) \
    $(wildcard include/config/usb/gadget/dwc2/otg.h) \
    $(wildcard include/config/fat/write.h) \
    $(wildcard include/config/mmc/sdhci.h) \
    $(wildcard include/config/partitions.h) \
    $(wildcard include/config/cmd/itest.h) \
    $(wildcard include/config/cmd/battery.h) \
    $(wildcard include/config/display/cpuinfo.h) \
    $(wildcard include/config/bootp/vci/string.h) \
    $(wildcard include/config/dm/spi/flash.h) \
    $(wildcard include/config/optee/tzdram/base.h) \
    $(wildcard include/config/cmd/gpio.h) \
    $(wildcard include/config/dm/usb.h) \
    $(wildcard include/config/bootstage/stash/size.h) \
    $(wildcard include/config/serial/present.h) \
    $(wildcard include/config/of/control.h) \
    $(wildcard include/config/fs/ext4.h) \
    $(wildcard include/config/spl/ldscript.h) \
    $(wildcard include/config/cmd/fdt.h) \
    $(wildcard include/config/cmd/loads.h) \
    $(wildcard include/config/cmd/fat.h) \
    $(wildcard include/config/usb/function/fastboot.h) \
    $(wildcard include/config/arch/exynos.h) \
    $(wildcard include/config/mkimage/dtc/path.h) \
    $(wildcard include/config/cmd/regulator.h) \
    $(wildcard include/config/cmd/pmic.h) \
    $(wildcard include/config/efi/partition/entries/off.h) \
    $(wildcard include/config/bounce/buffer.h) \
    $(wildcard include/config/cmd/net.h) \
    $(wildcard include/config/dfu/over/usb.h) \
    $(wildcard include/config/menu.h) \
    $(wildcard include/config/cons/index.h) \
    $(wildcard include/config/default/device/tree.h) \
    $(wildcard include/config/image/format/legacy.h) \
    $(wildcard include/config/net/tftp/vars.h) \
    $(wildcard include/config/spl/loglevel.h) \
    $(wildcard include/config/cmd/bootefi.h) \
    $(wildcard include/config/spl/gpio/support.h) \
    $(wildcard include/config/fit.h) \
    $(wildcard include/config/autoboot.h) \
    $(wildcard include/config/pinctrl/full.h) \
    $(wildcard include/config/dm.h) \
    $(wildcard include/config/bootp/gateway.h) \
    $(wildcard include/config/cmd/gpt.h) \
    $(wildcard include/config/dm/keyboard.h) \
    $(wildcard include/config/has/thumb2.h) \
    $(wildcard include/config/sys/malloc/f.h) \
    $(wildcard include/config/spl/printf.h) \
    $(wildcard include/config/cmd/tftpboot.h) \
    $(wildcard include/config/support/raw/initrd.h) \
    $(wildcard include/config/spl/use/arch/memcpy.h) \
    $(wildcard include/config/spl/payload.h) \
    $(wildcard include/config/cmd/importenv.h) \
    $(wildcard include/config/cmd/nvedit/efi.h) \
    $(wildcard include/config/strto.h) \
    $(wildcard include/config/pinctrl/generic.h) \
    $(wildcard include/config/sys/malloc/f/len.h) \
    $(wildcard include/config/mtdparts/default.h) \
    $(wildcard include/config/spl/partition/uuids.h) \
    $(wildcard include/config/tpl/banner/print.h) \
    $(wildcard include/config/dm/pmic/max17047.h) \
    $(wildcard include/config/cmd/elf.h) \
    $(wildcard include/config/pmic/children.h) \
    $(wildcard include/config/cmd/pxe.h) \
    $(wildcard include/config/image/sparse.h) \
    $(wildcard include/config/spl/libgeneric/support.h) \
    $(wildcard include/config/sys/arm/arch.h) \
    $(wildcard include/config/cmd/source.h) \
    $(wildcard include/config/dm/charger.h) \
    $(wildcard include/config/input.h) \
    $(wildcard include/config/log.h) \
  include/config_fallbacks.h \
    $(wildcard include/config/fallbacks/h.h) \
    $(wildcard include/config/spl/pad/to.h) \
    $(wildcard include/config/spl/max/size.h) \
    $(wildcard include/config/sys/baudrate/table.h) \
    $(wildcard include/config/cmd/kgdb.h) \
    $(wildcard include/config/sys/maxargs.h) \
    $(wildcard include/config/sys/i2c.h) \

spl/u-boot-spl.lds: $(deps_spl/u-boot-spl.lds)

$(deps_spl/u-boot-spl.lds):
